#############################################################
## JOB DESCRIPTION                                         ##
#############################################################

# NPT Equilibration

set temperature   290.5
#############################################################
## INPUT FILES                                            ##
#############################################################

# structure
coordinates        coordenades_inicials.pdb
structure          estructura_membranaDMPC.psf
set outputname     NPT

#set inputname      NPT
#binCoordinates     $inputname.restart.coor


# Input Force Field
paraTypeCharmm	    on
parameters        parametres.prm 

#############################################################
## SYSTEM SIZE AND BC                                      ##
#############################################################

# Periodic Boundary conditions
# NOTE: Do not set the periodic cell basis if you have also 
# specified an .xsc restart file!

#extendedSystem	$inputname.restart.xsc

cellBasisVector1   67.405998   0.   0.
cellBasisVector2     0.  57.295700  0.
cellBasisVector3     0.    0  69.111160
cellOrigin           0.0   0.0  0.0

wrapWater           on
wrapAll             on

#############################################################
## electrostatics and force field parameters               ##
#############################################################

# Force-Field Parameters
exclude             scaled1-4
1-4scaling          1.0
cutoff              12.
switching           on
switchdist          10.
pairlistdist        13.5

# PME (for full-system periodic electrostatics)
PME                 yes
PMEGridSizeX        72
PMEGridSizeY        60
PMEGridSizeZ        72

#############################################################
## INTEGRATION ALGORITHMS AND THERMODYNAMIC ENSEMBLE       ##
#############################################################


# Integrator Parameters
timestep            2.0  ;# 2fs/step
rigidBonds          all  ;# needed for 2fs steps
nonbondedFreq       1

fullElectFrequency  2  
stepspercycle       10


# Constant Temperature Control
temperature         $temperature

langevin            on    ;# do langevin dynamics
langevinDamping     1     ;# damping coefficient (gamma) of 1/ps
langevinTemp        $temperature
langevinHydrogen    off    ;# don't couple langevin bath to hydrogens

# Constant Pressure Control (variable volume)
useGroupPressure      yes ;# needed for 2fs steps
useFlexibleCell       yes  ;# no for water box, yes for membrane
useConstantArea       yes  ;# no for water box, yes for membrane

langevinPiston        on
langevinPistonTarget  1.01325 ;#  in bar -> 1 atm
langevinPistonPeriod  200.
langevinPistonDecay   100.
langevinPistonTemp    $temperature



# Output
outputName          $outputname

restartfreq         50000     ;# 50000 steps = every 100ps
dcdfreq             10000	     ;# 10000 steps = every 20ps
xstFreq             50000
outputEnergies      10000
outputPressure      10000


#############################################################
## EXTRA PARAMETERS                                        ##
#############################################################


#############################################################
## EXECUTION SCRIPT                                        ##
#############################################################


numsteps 1000000 ;# 2ns





