#############################################################
## JOB DESCRIPTION                                         ##
#############################################################

# NVT Production

set temperature   209.5
#############################################################
## INPUT FILES                                            ##
#############################################################

# structure
coordinates       coordenades_inicials.pdb
structure          estructura_membranaDMPC.psf
set outputname     NVT

set inputname      ../Equilibrat_NPT/NPT
binCoordinates     NPT.restart.coor


# Input Force Field
paraTypeCharmm	    on
parameters        parametres.prm 

#############################################################
## SYSTEM SIZE AND BC                                      ##
#############################################################

# Periodic Boundary conditions
# NOTE: Do not set the periodic cell basis if you have also 
# specified an .xsc restart file!

extendedSystem	NPT.restart.xsc

wrapWater           on
wrapAll             on

#############################################################
## electrostatics and force field parameters               ##
#############################################################

# Force-Field Parameters
exclude             scaled1-4
1-4scaling          1.0
cutoff              12.
switching           on
switchdist          10.
pairlistdist        13.5

# PME (for full-system periodic electrostatics)
PME                 yes
PMEGridSizeX        72
PMEGridSizeY        60
PMEGridSizeZ        72

#############################################################
## INTEGRATION ALGORITHMS AND THERMODYNAMIC ENSEMBLE       ##
#############################################################


# Integrator Parameters
timestep            2.0  ;# 2fs/step
rigidBonds          all  ;# needed for 2fs steps
nonbondedFreq       1

fullElectFrequency  2  
stepspercycle       10


# Constant Temperature Control
temperature         $temperature

langevin            on    ;# do langevin dynamics
langevinDamping     1     ;# damping coefficient (gamma) of 1/ps
langevinTemp        $temperature
langevinHydrogen    off    ;# don't couple langevin bath to hydrogens

# Constant Pressure Control (variable volume)
useGroupPressure      no ;# needed for 2fs steps
useFlexibleCell       yes  ;# no for water box, yes for membrane
useConstantArea       yes  ;# no for water box, yes for membrane

langevinPiston        on
langevinPistonTarget  1.01325 ;#  in bar -> 1 atm
langevinPistonPeriod  200.
langevinPistonDecay   100.
langevinPistonTemp    $temperature



# Output
outputName          $outputname

restartfreq         5000     ;# 5000 steps = every 10ps
dcdfreq             10	     ;# 10 steps = every 20fs
xstFreq             5000
outputEnergies      1000
outputPressure      1000


#############################################################
## EXTRA PARAMETERS                                        ##
#############################################################


#############################################################
## EXECUTION SCRIPT                                        ##
#############################################################
# Minimization


numsteps 5000





